name: sem-deep-learning
channels:
  - pytorch
dependencies:
  - pytorch
  - torchvision
  - pip
  - pip:
    - torchsummary
    - pytorch-lightning
    - tensorboard
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - coverage